---
title: "Viz Examples"
output:
  html_document:
    keep_md: true
---



```{r setup}

require(ggplot2)

```

```{r get-data}
options(stringsAsFactors=F)
#require(plyr)
df=read.csv("20140805_Raw_Data.csv",stringsAsFactors=F) #legacy name
#df=(df[order(df$Profit.in.Millions),])
df$Profit.in.Millions=df$Profit/1e6
df$Opening.Date=as.Date(df$Opening.Date,"%d-%b-%y")
df$Withdrawl.Date=as.Date(df$Withdrawl.Date,"%d-%b-%y")
df$pl="P"
df$pl[df$Profit<=0]="L"
df$Financial.Year=factor(df$Financial.Year,levels=sort(unique(df$Financial.Year)))
str(df)
```
Let's see what we have, scatterplots first

```{r scatters}
require(ggplot2)
require(scales)
gscat=ggplot(df,aes(x=Days,y=Profit.in.Millions,color=Financial.Year,group=df$Earnings.Type))+geom_point(aes(shape=df$Earnings.Type))
print(gscat)
gscat=ggplot(df,aes(x=Gross.Earnings,y=Profit.in.Millions,color=Financial.Year,group=df$Earnings.Type))+geom_point(aes(shape=df$Earnings.Type))
print(gscat)
```


```{r histogram}
ghist=ggplot(df,aes(x=Profit.in.Millions)) + geom_histogram(binwidth=5)+facet_grid(Financial.Year~.)
print(ghist)
```

```{r stacked-bar}
df=df[order(df$Cut.Start,df$Earnings.Type),]
gbar=ggplot(df[df$Profit>0,],aes(x=factor(Cut.Start),y=Profit,fill=Earnings.Type))+geom_bar(stat="identity",)+facet_grid(Financial.Year~.)+coord_flip()
print(gbar)
gbar=ggplot(df[df$Profit<=0,],aes(x=factor(Cut.Start),y=Profit*-1,fill=Earnings.Type))+geom_bar(stat="identity",)+facet_grid(Financial.Year~.)+coord_flip()
print(gbar)
```


```{r spiffy}
df$base=0
gspiffy=ggplot(df,aes(x=Profit,y=Gross.Earnings))+geom_rect(xmin=df$Cut.Start,xmax=df$Cut.End,ymin=df$base,ymax=df$Profit)
print(gspiffy)
```

```{r backtoback}
df=df[order(df$Financial.Year,df$Earnings.Type,df$Profit),]
gbb=ggplot(df,aes(x=Financial.Year))+
  geom_bar(data = subset(df, Profit>0),aes(y=Profit,fill=Earnings.Type),stat="identity")+
  geom_bar(data = subset(df, Profit<=0),aes(y=Profit,fill=Earnings.Type),stat="identity")
#scale_fill_gradient2(low = muted("red"),mid = "white", high = muted("black"), midpoint = 0,space = "rgb")
#facet_grid(Financial.Year~.)+coord_flip()
print(gbb)

```



```{r backtoback2}
df=df[order(df$Financial.Year,df$Profit),]
gbb=ggplot(df,aes(x=Financial.Year))+
  geom_bar(data = subset(df, pl=="P"),aes(y=Profit.in.Millions,fill=Profit.in.Millions),stat="identity")+
  geom_bar(data = subset(df, pl=="L"),aes(y=Profit.in.Millions,fill=Profit.in.Millions),stat="identity")+
   scale_y_continuous(labels = comma) +  theme_bw()+
  ylab("Profit - Loss") + 
  geom_hline(yintercept = 0,colour = "black") +
scale_fill_gradient2(low = muted("red"),mid = "white", high = muted("black"), midpoint = 0,space = "rgb")
print(gbb)

```


```{r backtoback3}
df=df[order(df$Financial.Year,df$Earnings.Type,df$pl),]
gbb3=ggplot(df,aes(x=Financial.Year))+
  geom_bar(data = subset(df, pl=="P"),aes(y=Profit.in.Millions,fill=Earnings.Type),stat="identity")+
  geom_bar(data = subset(df, pl=="L"),aes(y=Profit.in.Millions,fill=Earnings.Type),stat="identity")+
   scale_y_continuous(labels = comma, limits=c(-10,50)) +  theme_bw()+
  ylab("Profit - Loss") + 
  geom_hline(yintercept = 0,colour = "black") 
print(gbb3)

```
